site_name: Payday 2 BLT Documentation
site_author: James Wilkinson
repo_url: https://github.com/JamesWilko/Payday-2-BLT-Docs
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['globals/variables.md', 'Lua Globals', 'Global Variables']
- ['globals/functions.md', 'Lua Globals', 'Global Functions']
- ['globals/file.md', 'Lua Globals', 'Files and IO']
- ['mod_definition.md', 'Mod Definition', 'Mod Definition File']
- ['lua/localization.md', 'Lua', 'Localization']
- ['lua/hooks.md', 'Lua', 'Hooks']
- ['lua/delayed_calls.md', 'Lua', 'Delayed Calls']
- ['lua/notifications.md', 'Lua', 'Notifications']
- ['lua/json.md', 'Lua', 'Json']
- ['lua/utils.md', 'Lua', 'Utilities']
- ['lua/menu/menu_helper.md', 'Menus', 'Menu Helper']
- ['lua/menu/menu_helper_hooks.md', 'Menus', 'Menu Helper Hooks']
- ['lua/menu/json_menu.md', 'Menus', 'Json Menus']
- ['lua/network/network.md', 'Networking', 'LuaNetwork']
- ['lua/network/hooks.md', 'Networking', 'Hooks']
- ['lua/network/extensions.md', 'Networking', 'Extensions']
